# Generated by Django 2.2 on 2019-04-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapi', '0002_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='governmentId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='analysisapi.Government'),
            preserve_default=False,
        ),
    ]
